#!/bin/bash

set -eu


## ============================================================================


INVOICE_PATH=""

while [[ $# -gt 0 ]]; do
    case "${1}" in
        --help|-h)
            SCRIPT_NAME=$(basename "$(readlink -f "${BASH_SOURCE[@]}")")
            echo "usage: ${SCRIPT_NAME} [--invoice|-i <path>] [--help|-h]"
            echo
            echo "Send invoices to KSeF using active profile."
            echo
            echo "options:"
            echo "  -h, --help                  show this help"
            echo "  -i, --invoice               path to invoice XML file"
            exit 0
            ;;

        --invoice=*|-i=*)
            INVOICE_PATH="${1#*=}"
            shift
            ;;
        --invoice|-i)
            INVOICE_PATH="${2}"
            shift 2
            ;;

        *)
            echo "unknown argument: ${1}"
            exit 1
            ;;

    esac
done


## ============================================================================


echo "===== Sending invoice ====="

ksef send online --invoice "${INVOICE_PATH}" --wait-status --wait-upo


echo
echo "Processing completed"
